on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag qbit-issue-tracker
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Tag the Docker image with latest
      run: docker tag qbit-issue-tracker ghcr.io/${{ github.repository_owner }}/qbit-issue-tracker:latest
    - name: Tag the Docker image with commit SHA
      run: docker tag qbit-issue-tracker ghcr.io/${{ github.repository_owner }}/qbit-issue-tracker:${{ github.sha }}
    - name: Push the Docker image with latest
      run: docker push ghcr.io/${{ github.repository_owner }}/qbit-issue-tracker:latest
    - name: Push the Docker image with commit SHA
      run: docker push ghcr.io/${{ github.repository_owner }}/qbit-issue-tracker:${{ github.sha }}
